### ISSUE TITLE
Informative log instead of printing  'execution reverted: EPOCH_IS_TOO_OLD' traceback

### ISSUE THREAD

**Issue by ongrid** [lidofinance/lido-oracle#44]
When local TX call fails on the line,

https://github.com/lidofinance/lido-oracle/blob/86d343dc415d373892c7aefdd38713787b55fc9a/app/oracle.py#L195 

the daemon prints traceback, and it can be perceived by the user that something went wrong (Looks exactly as the "traceback of the death"). Moreover, the process after it pauses for WAIT time.

```
ERROR 2020-11-27 13:06:46 <daemon> Unexpected exception. 
Traceback (most recent call last):
  File "oracle.py", line 191, in <module>
    w3.eth.call(tx)
  File "/usr/local/lib/python3.8/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/web3/eth.py", line 432, in call
    return self.web3.manager.request_blocking(
  File "/usr/local/lib/python3.8/site-packages/web3/manager.py", line 153, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': 3, 'message': 'execution reverted: EPOCH_IS_TOO_OLD', 'data': '0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001045504f43485f49535f544f4f5f4f4c4400000000000000000000000000000000'}
    INFO 2020-11-27 13:06:46 <daemon> Sleep 60 s.
```

What should be done just now:
* If Traceback matches "execution reverted: EPOCH_IS_TOO_OLD" substring, the daemon should display descriptive one-line WARN ing
* Recommend longer WAIT time for production (about one hour will be enough to make such race of reports very unlikely)

How to improve algorithm more dramatically:
* Preliminary reason of this - oracle  daemons tend to synchronize their loops to the moment of frame switching on ETH1 side. With aggressive timing - oracles observe this nearly simultaneously and try to poll and report. Only first N (where N=quorum) will succeed.
* In the wider scope, the algorithm should be improved to avoid such synchronisation issues, will clarify the proposal in #21

**Comment by skozin** [comment]
Do you mean the check implemented here?

https://github.com/lidofinance/lido-oracle/commit/d91fbf221bfe0dbe53876d7fadc4dae4c762935c#diff-2962d36a8e34a32a6e4fc3c91dc3061a5a07bae71f655fbe4b3aaded2a390a63R200

**Comment by ujenjt** [comment]
Already fixed, please ping me for details

**Comment by ongrid** [comment]
Pyrmont's commit branch is a good to pick. Need to import SolidityError and catch two known results of the call and log them as `info`. Unknown exceptions should be logged as `error`. 
```
    except SolidityError as sl:
        str_sl = str(sl)
        if "EPOCH_IS_TOO_OLD" in str_sl:
            logging.info(f'Frame already finalized, skipping...')
        elif "ALREADY_SUBMITTED" in str_sl:
            logging.info(f'Frame already reported, skipping...')
        else:
            logging.error(f'Running tx failed: {str_sl}')
```

Test this within E2E visually. At least `EPOCH_IS_TOO_OLD` happens under normal conditions. Sniff the tcpdump of web3 call and parse the stream, erroneous request/response pairs are in the focus, we'll need it later for integration tests.

The example of recorded web3 JSON RPC trace (I've got it via ''Follow HTTP stream of the WireShark")
```
POST /rpc HTTP/1.1
Host: 206.81.31.11
User-Agent: Web3.py/5.13.0/<class 'web3.providers.rpc.HTTPProvider'>
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Type: application/json
Content-Length: 66

{"jsonrpc": "2.0", "method": "eth_chainId", "params": [], "id": 0}HTTP/1.1 200 OK
Server: nginx/1.19.4
Date: Tue, 01 Dec 2020 16:48:10 GMT
Content-Type: application/json
Content-Length: 64
Connection: keep-alive
Content-Encoding: gzip
Vary: Origin

{"jsonrpc":"2.0","id":0,"result":"0x5"}
POST /rpc HTTP/1.1
Host: 206.81.31.11
User-Agent: Web3.py/5.13.0/<class 'web3.providers.rpc.HTTPProvider'>
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Type: application/json
Content-Length: 70

{"jsonrpc": "2.0", "method": "eth_blockNumber", "params": [], "id": 1}HTTP/1.1 200 OK
Server: nginx/1.19.4
Date: Tue, 01 Dec 2020 16:48:10 GMT
Content-Type: application/json
Content-Length: 69
Connection: keep-alive
Content-Encoding: gzip
Vary: Origin

{"jsonrpc":"2.0","id":1,"result":"0x3ac3f6"}
POST /rpc HTTP/1.1
Host: 206.81.31.11
User-Agent: Web3.py/5.13.0/<class 'web3.providers.rpc.HTTPProvider'>
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Type: application/json
Content-Length: 73
```

Base branch `daemon_v2, HEAD`
PR back to `daemon_v2`

**Comment by ongrid** [comment]
discussed verbally with @vsmelov, it seems possible to unit-test the new behavior without networking mock.
