### ISSUE TITLE
Prometheus Metrics

### ISSUE THREAD

**Issue by joe-bowman** [lidofinance/lido-oracle#56]
The oracle should expose a prometheus metrics endpoint, to track vital values (e.g. eth balance, block heights, etc.)

**Comment by ongrid** [comment]
Hey @joe-bowman. We are considering to implement one of two possible options:
* Make the oracle daemon "scrapeable". It should expose HTTP Endpoint that will be polled by Prometheus. You mean this option, right? This needs more configuration and more efforts to protect the endpoint from external threats.
* Exporting (pushing) metrics to the Prometheus gateway. This approach seems to be more secure (less exposure, less attack surface). Does it suit your and typical Prometheus setup?

**Comment by joe-bowman** [comment]
Scrapable (pull model) is preferred, push model comes with caveats (less trivial to assert something is ‘down’ because push gateway will keep the last value. It can be worked around, by pushing a counter with the current unix time as a value (last_push) so you can alert on that not increasing.

Pull is preferred from a ops point of view, but appreciate the desire to minimise attack surface.

**Comment by vshvsh** [comment]
@joe-bowman we're now discussing a decision which is a blocker to implementing the metrics. 
Should an oracle run as a daemon (and export metrics over an endpoint) or a cronable single-run executable (can write metrics to file that is served by a separate exporter)? 
Given that the oracle is stateless currently, and should fire once per day at a predictable time, I'd prefer the second option for the time being. What do you think?

**Comment by ongrid** [comment]
The daemon runs in the docker container and won't rely on any task sheduler. The container and the process inside are always up (the main oracle coroutine sleeps and wakes up once a day or several hours). This doesn't prevent another coroutine to serve external scrap requests or export values to the Prometheus GW using built-in async mechanisms. So both options are possible. The Exporting (pushing) just needs less efforts in terms of security and more efforts on mainainer's side to configure Prometheus GW.

I'd prefer to give our operators option 1 (scrapable) but with the strong requirement to run the container inside the perimeter + introduce in-process whitelisting + kernel-level firewall rules. On the later stage I'd extend the option 1 with some proven authorization mechanism.

**Comment by joe-bowman** [comment]
Push works for me; I appreciate the desire to minimise attack surface.

Presumably it fires more frequently than once a day though? (i.e. each time it polls for new blocks). We don't want to only find out it is down when it has failed to update. Being alerted early to the fact it is not syncing is very useful.

**Comment by vshvsh** [comment]
The "real" run is once/day on mainnet, but we can have an arbitrary number of dry runs (e.g. 1/hour).

**Comment by ongrid** [comment]
# Metrics overview:

## Overall metrics of Lido

### Collected from ETH1 via web3

Ether in the system:
* Ether.Deposited from `Lido.getBeaconStat()[0] * DEPOSIT_SIZE`
* Ether.Buffered from `Lido.getBufferedEther()`
* Ether.OnBeacon.Reported from `Lido.getBeaconStat()[2]`

Lido Validators:
* Validators.Keys from NOPs registry
* Validators.Deposited from `getBeaconStat()[0]`
* Validators.OnBeacon (Contract View) from `getBeaconStat()[1]`

stETH supply and balances:
* stETH.totalSupply | Gauge |  
* stETH.onTreasury | Gauge |  
* stETH.onInsurance | Gauge |  
* stETH.onOperators | Gauge |  
* stETH.onCstETH | Gauge |  
* stETH holders
* stETH.totalHolders | Counter |  

cstETH:
* CstETH.totalSupply | Gauge |  
* cstETH.totalHolders | Counter | 

Mined Txes to the Lido. To be rendered as Histogram. Visibility of net performance and funding ingress.
* `Submit` Tx quantity (separated by status: reverted or Successful) and ETH values
* Other transactions/logs counters (including oracle reports, pushes, depositBufferedEthers).

MemPool stats - visibility of network weather. To be rendered as Histogram
* Txes. Pending - The number of txes targeted to Lido visible in ETH1 node mempool
* Ethers. Pending - The amount of ethers to the Lido contract in TX mempool (visibility of funds in the mempool

### Collected from NOP's oracle daemon instance

* Ether.OnBeacon (check for correct naming)
* Oracle Frames with individual reports and quorum values (to be rendered as Histogram in Grafana?)

## Individual NOP-related metrics

### Infrastructure metrics from ETH1 and Beacon nodes (Geth and Lighthouse)
* eth1_block_number - tracked for each ETH1 node of NOP (infrastructure monitoring).
* beacon slot and epoch - tracked for each beacon node of NOP (infrastructure monitoring).
* beacon finalized slot and epoch - tracked for each beacon node of NOP (infrastructure monitoring).

### Collected from ETH1 and Beacon states (via beacon client and web3)
* Eth balance of NOP's Member account
* networks [(mainnet / goerli)(mainnet, pyrmont, medalla ) to which the ETH1 and Beacon nodes connected

### Collected from NOP's oracle daemon instance
* oracle daemon/container status (running/stopped)
* last oracle run timestamp
* next oracle run timestamp
* attrs and method call results of `previous` and `current` metrics: `epoch`, `beaconBalance`, `beaconValidators`, `timestamp`, `bufferedBalance`, `depositedValidators`, `activeValidatorBalance`, `getTotalPooledEther()`, `getTransientValidators()`, `getTransientBalance()`. Collected by oracle daemon
* deltas from compare_pool_metrics(): `warnings`, delta_seconds, appeared_validators, timedelta, depositedValidatorsChange, appearedValidators, transientValidatorsChange, transientBalanceChange, totalPooledEtherChange, reward_base, apr, reward. Collected by oracle daemon.
* network (mainnet / goerli / e2e) to which the oracle daemon connected
* version and metadata of oracle daemon, GAS_LIMIT, SLEEP

[https://github.com/GuillaumeMiralles/prysm-grafana-dashboard] for individual NOPs validators and balances

**Comment by ongrid** [comment]
@vshvsh could you please verify and confirm the overall vision and scope of the current issue?

**Comment by vshvsh** [comment]
On the first glance there's too much, will get back to you soon

**Comment by vshvsh** [comment]
Ah, I see, most of it is not in scope.

What are the typical problematic outcomes of an oracle:
1. It didn't deliver a data point when it should have
2. It delivered a wrong/dangerous data point

So we need metrics that help people to prevent both those outcomes.

The list above solves most of it but I'd like to see two more very important metrics:

Metric of "time since last possible oracle report and an actual oracle report transaction from me" - so if you're operating normally, it'll never grow beyond a few minutes but if your oracle skips report for whatever reason op gets an alert when it reaches 10m or something.

And metric of "Number of distinct reported values in the last oracle reports", if it's ever >1 it's an alert.

**Comment by ongrid** [comment]
All of this seem to be also out of oracle daemon exporter's scope. This should be observed via *ETH1-Prometheus middleware* from the main source of truth - contract states and their events similarly to the following piece of code [ethexporter](https://github.com/hunterlong/ethexporter). And better to do it through the several ETH1 endpoints and then plot on the single view in Grafana. Most of time the numbers will visually be merged into one line and any deviation (node freeze or peers loss for example) will spread the lines.

I've added:

"time since last possible oracle report and an actual oracle report transaction from me" (+expanded a little) to Individual NOP-related metrics -> Collected from ETH1 via web3
 
Number of distinct reported values in the last oracle reports: to Overall metrics of Lido -> Collected from ETH1 via web3

**Comment by ongrid** [comment]
Discussed with @vsmelov: ETH1-Prometheus-middleware and Beacon-Promentheus-middleware to be implemented as an independent exporter in the separate repository similarly to https://github.com/certusone/chainlink_exporter.

Oracle-Daemon-Prometheus exporter will stay in the oracle daemon.
